name: Docker Image Publish

on:
  release:
    types: [published]
  push:
    branches: [ "main" ]
    # Publish semver tags as releases.
    #tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ "main" ]

jobs:
  steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        push: true