name: Hello Action
on: [push]

jobs:
  print:
    runs-on: ubuntu-latest
    steps:
      - name: Add repo
        uses: actions/checkout@v4
      - name: Set up python3
        uses: actions/setup-python@v5
        with:
          python-version: '3.10' 
      - name: Run hello script
        run: python hello.py
       