name: "Create cluster using KinD"
on: [push]

jobs:
  kind:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository  
        uses: actions/checkout@master
      - name: Setup kind
        uses: engineerd/setup-kind@v0.5.0
        with:
          version: "v0.11.1"
      - name: Testing
        run: |
          kubectl cluster-info > Info
          kubectl get pods -n kube-system > Pods
          echo "current-context:" $(kubectl config current-context) 
          echo "environment-kubeconfig:" ${KUBECONFIG} 
          echo "Info" $Info
          echo "Pods" $Pods
     