name: Check pods
on: [push]
  #workflow_dispatch:
jobs:
  pods:
    runs-on: ubuntu-latest
    steps:
      - name: SSH connect to remoute host
        id: kube_pod
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          proxy_host: ${{ secrets.PROXY_HOST }}
          proxy_username: ${{ secrets.PROXY_USERNAME }}
          proxy_key: ${{ secrets.PROXY_KEY }}
          proxy_port: ${{ secrets.PROXY_PORT }}
          script: |
            kubectl get pods -A --context="k3s" > k3s.log
            kubectl get pods -A --context="k8s" > k8s.log
            {"k3s_log=$(cat k3s.log)" "k8s_log=$(cat k8s.log)" } >> $GITHUB_OUTPUT
           
      - name: Check Crash pods
        id: count_faild_pods
        run: |
            echo "steps.kube_pod.outputs.k3s.log" > k3s_out.log
            echo "steps.kube_pod.outputs.k8s.log" > k8s_out.log
            { 
              "fail_pods_k3s=$(cat k3s_out.log | grep -v 'Running\|Completed ' | wc -l)"
              "fail_pods_k8s=$(cat k8s_out.log | grep -v 'Running\|Completed ' | wc -l)"
            } >> $GITHUB_OUTPUT
             
        shell: bash

      - name: Upload Crashed Pods List k3s
        if: steps.count_faild_pods.outputs.fail_pods_k3s != 0 
        uses: actions/upload-artifact@v4
        with:
            name: Dead pods 
            path: k3s_out.log
      - name: Upload Crashed Pods List k3s      
        if: steps.count_faild_pods.outputs.fail_pods_k8s != 0 
        uses: actions/upload-artifact@v4
        with:
            name: Dead pods 
            path: k8s_out.log