name: Check pods
on: [push]
  #workflow_dispatch:
jobs:
  pods:
    runs-on: ubuntu-latest
    steps:

      - name: SSH connect to remoute host
        id: kube_pod
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          proxy_host: ${{ secrets.PROXY_HOST }}
          proxy_username: ${{ secrets.PROXY_USERNAME }}
          proxy_key: ${{ secrets.PROXY_KEY }}
          proxy_port: ${{ secrets.PROXY_PORT }} #-v
          script: |
            kubectl get pods -A --context="k8s" | grep 'Running\|Completed ' > k8s.log   
            echo "::set-output name=k8s_log::$(cat k8s.log)"
            echo "::set-output name=k8s_count::$(cat k8s.log | wc -l)"
            
           
      - name: Check Crash pods
        id: form_file 
        run: |
            echo ${{steps.kube_pod.outputs.k8s_log}} > k8s.log 
            echo ${steps.kube_pod.outputs.k8s_count}
            echo "steps.kube_pod.outputs.k8s_count"
        shell: bash    

            
        
      - name: Upload Crashed Pods List k3s 
        if: steps.kube_pod.outputs.k8s_count != 0 
        uses: actions/upload-artifact@v4
        with:
            name: Failed pods 
            path: k8s.log

       