name: helm-flask-app-psql
on: [ workflow_dispatch ]
jobs:
  release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |        
          git config user.name "nataliabelogolovaya"
          git config user.email "belogolovayanv@gmail.com"
     
      - name: Install Helm
        uses: azure/setup-helm@v3     
      
      - name: package creating
        run: |
          ls -al 
          helm package flask-psql
          VAR="$(find ./ -name "flask-psql-*" )"
          echo "this is $VAR"          
          cp $VAR flask-psql
          helm repo index flask-psql
          cat flask-psql/index.yaml
        shell: bash

      - name: Publish
        uses: selenehyun/gh-push@master
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN_HELM }}
          COMMIT_FILES: flask-psql/*
          REPO_FULLNAME: NataliaBelogolovaya/helm_pages
          BRANCH: main 

