name: helm-flask-app-psql
on: [ workflow_dispatch, push ]
jobs:
  release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$nataliabelogolovaya"
          git config user.email "belogolovayanv@gmail.com"
     
      - name: Install Helm
        uses: azure/setup-helm@v3     
      
      - name: package creating
        run: |
          ls -al 
          helm package flask-psql
          VAR="$(find ./ -name "flask-psql-*" )"
          echo "this is $VAR"
          helm repo index flask-psql  
          cat flask-psql/index.yaml
          cp $VAR flask-psql
        shell: bash

      - name: pull
        uses: antaljanosbenjamin/single-commit-publish@master
        with:
          github-token: ${{ secrets.TOKEN_HELM }}
          branch: gh_pages
          source-dir: flask-psql
          files-and-dirs: "${{ github.workspace }}/flask-psql"    


      #- name: Run chart-releaser
       # uses: helm/chart-releaser-action@v1.6.0
       # with:
        #  charts_dir: flask-psql
        #env:
         # CR_TOKEN: "${{ secrets.TOKEN_HELM }}"

      
